'use client';
import { useEffect, useState } from 'react';
import { BookOpen, Brain, BriefcaseBusiness, CalendarDays, ChevronRight, CircleUserRound, Home, Menu, Plus, Save, Sparkles, Target, X } from 'lucide-react';
import { ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, Radar, Tooltip } from 'recharts';
import { actions, entries as seedEntries, evidence, jobs, skills, type Entry, type SkillKey } from '@/data/mock';
import { evidenceForSkill, gapsFor, roleNames, targetFor, type RoleName } from '@/lib/career';

type Page = 'home'|'journal'|'skills'|'memory'|'jobs';
const nav = [{id:'home',label:'Home',icon:Home},{id:'journal',label:'Career Journal',icon:CalendarDays},{id:'skills',label:'Skill Map',icon:Target},{id:'memory',label:'Career Memory',icon:Brain},{id:'jobs',label:'Job Tracker',icon:BriefcaseBusiness}] as const;
const fmt=(d:string)=>new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric'}).format(new Date(d+'T12:00:00'));
const storageKeys = { entries:'career-agent.entries.v1', role:'career-agent.role.v1', actions:'career-agent.actions.v1' } as const;

export default function App(){
 const [page,setPage]=useState<Page>('home'); const [role,setRole]=useState<RoleName>('GTM'); const [entries,setEntries]=useState(seedEntries); const [mobile,setMobile]=useState(false);
 const [selectedEntry,setSelectedEntry]=useState<Entry|undefined>(seedEntries[0]); const [skill,setSkill]=useState<SkillKey>('gtm');
 const [completedActions,setCompletedActions]=useState<number[]>([]); const [storageReady,setStorageReady]=useState(false);
 useEffect(()=>{try{const savedEntries=localStorage.getItem(storageKeys.entries);const savedRole=localStorage.getItem(storageKeys.role);const savedActions=localStorage.getItem(storageKeys.actions);if(savedEntries)setEntries(JSON.parse(savedEntries));if(savedRole&&roleNames.includes(savedRole as RoleName))setRole(savedRole as RoleName);if(savedActions)setCompletedActions(JSON.parse(savedActions))}catch{}finally{setStorageReady(true)}},[]);
 useEffect(()=>{if(!storageReady)return;localStorage.setItem(storageKeys.entries,JSON.stringify(entries));localStorage.setItem(storageKeys.role,role);localStorage.setItem(storageKeys.actions,JSON.stringify(completedActions))},[entries,role,completedActions,storageReady]);
 const go=(p:Page)=>{setPage(p);setMobile(false)};
 return <div className="shell">
  <aside className={`sidebar ${mobile?'open':''}`}><div className="brand"><span className="brandmark">C</span><span>Career Agent</span></div><button className="close mobile" aria-label="关闭菜单" onClick={()=>setMobile(false)}><X/></button>
   <nav>{nav.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>go(n.id)}><n.icon/><span>{n.label}</span></button>)}</nav>
   <div className="profile"><CircleUserRound/><span>我的职业账户</span></div>
  </aside>
  {mobile&&<button className="scrim" aria-label="关闭菜单" onClick={()=>setMobile(false)}/>} 
  <main><header><button className="menu mobile" aria-label="打开菜单" onClick={()=>setMobile(true)}><Menu/></button><div><p className="eyeline">Career workspace</p><h1>{page==='home'?'早上好，今天想记录什么？':nav.find(n=>n.id===page)?.label}</h1></div><div className="header-date">2026年9月4日 · 周五</div></header>
   {page==='home'&&<HomePage role={role} setRole={setRole} entries={entries} setEntries={setEntries} completedActions={completedActions} setCompletedActions={setCompletedActions} openEntry={e=>{setSelectedEntry(e);go('journal')}} openSkill={s=>{setSkill(s);go('skills')}}/>}
   {page==='journal'&&<Journal entries={entries} selected={selectedEntry} select={setSelectedEntry} openSkill={s=>{setSkill(s);go('skills')}}/>}
   {page==='skills'&&<SkillMap role={role} setRole={setRole} selected={skill} select={setSkill} openEntry={e=>{setSelectedEntry(e);go('journal')}}/>}
   {page==='memory'&&<Memory openEntry={e=>{setSelectedEntry(e);go('journal')}} openSkill={s=>{setSkill(s);go('skills')}}/>}
   {page==='jobs'&&<Jobs/>}
  </main>
  <button className="fab mobile" aria-label="快速记录" onClick={()=>go('home')}><Plus/></button>
 </div>
}

function PageHead({title,copy,right}:{title:string;copy:string;right?:React.ReactNode}){return <div className="pagehead"><div><h2>{title}</h2><p>{copy}</p></div>{right}</div>}
function RoleSelect({role,setRole}:{role:RoleName;setRole:(r:RoleName)=>void}){return <label className="role-select"><span>Target Role</span><select value={role} onChange={e=>setRole(e.target.value as RoleName)}>{roleNames.map(r=><option key={r}>{r}</option>)}</select></label>}

function HomePage({role,setRole,entries,setEntries,completedActions,setCompletedActions,openEntry,openSkill}:{role:RoleName;setRole:(r:RoleName)=>void;entries:Entry[];setEntries:(e:Entry[])=>void;completedActions:number[];setCompletedActions:(v:number[])=>void;openEntry:(e:Entry)=>void;openSkill:(s:SkillKey)=>void}){
 const [text,setText]=useState(''); const [saved,setSaved]=useState(false); const gaps=gapsFor(role).slice(0,3);
 const save=()=>{if(!text.trim())return; const item:Entry={id:'local-'+Date.now(),date:'2026-09-04',title:text.slice(0,24),type:'随记',summary:text,reflection:'待后续由 AI structured output 补全。',skills:['user'],evidenceIds:[],signal:'New reflection'}; setEntries([item,...entries]);setText('');setSaved(true);setTimeout(()=>setSaved(false),1800)};
 return <div className="content home-grid">
  <section className="capture panel"><div className="section-title"><div><h2>Quick Capture</h2><p>先记下真实经历，结构化可以稍后发生。</p></div><Sparkles/></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="记录想法、观察、学习、成就或问题…"/><div className="capture-foot"><span>{saved?'已保存到 Career Journal':'⌘ Enter 快速保存'}</span><button className="primary" onClick={save}><Save/>保存为 Career Entry</button></div></section>
  <section className="role panel"><div className="section-title"><div><p>Primary Role</p><h2>{role}</h2></div><Target/></div><RoleSelect role={role} setRole={setRole}/><div className="role-meta"><span>时间范围</span><b>6–12 个月</b></div><div className="role-meta"><span>重点</span><b>用证据缩小能力差距</b></div></section>
  <section className="gaps panel"><div className="section-title"><h2>Top Skill Gaps</h2><button className="link" onClick={()=>openSkill(gaps[0].id)}>查看全部 <ChevronRight/></button></div>{gaps.map((g,i)=><button className="gap-row" key={g.id} onClick={()=>openSkill(g.id)}><span className="rank">{i+1}</span><span className="grow"><b>{g.name}</b><i><em style={{width:`${g.current/targetFor(g,role)*100}%`}}/></i><small>Current L{g.current} · Target L{targetFor(g,role)}</small></span><strong>Gap {g.gap}</strong></button>)}</section>
  <section className="actions panel"><div className="section-title"><h2>本周主动争取</h2><span>{completedActions.length}/3 完成</span></div>{actions.map((a,i)=><label className="action" key={a}><input type="checkbox" checked={completedActions.includes(i)} onChange={()=>setCompletedActions(completedActions.includes(i)?completedActions.filter(x=>x!==i):[...completedActions,i])}/><span><b>{a}</b><small>{['把执行工作向前延伸到策略输入','形成一份可复用的分析证据','补足 Product Launch 场景理解'][i]}</small></span></label>)}</section>
  <section className="recent panel"><div className="section-title"><h2>最近记录</h2><button className="link" onClick={()=>openEntry(entries[0])}>打开 Journal <ChevronRight/></button></div>{entries.slice(0,4).map(e=><button className="entry-row" key={e.id} onClick={()=>openEntry(e)}><BookOpen/><span className="grow"><b>{e.title}</b><small>{e.summary}</small></span><span className="type">{e.type}</span><time>{fmt(e.date)}</time><ChevronRight/></button>)}</section>
 </div>
}

function Journal({entries,selected,select,openSkill}:{entries:Entry[];selected?:Entry;select:(e:Entry)=>void;openSkill:(s:SkillKey)=>void}){
 const [view,setView]=useState<'calendar'|'timeline'|'heatmap'>('calendar'); const days=Array.from({length:35},(_,i)=>i-1); const byDay=new Map(entries.filter(e=>e.date.startsWith('2026-09')).map(e=>[Number(e.date.slice(-2)),e]));
 return <div className="content"><PageHead title="Career Journal" copy="在时间里看见经历如何变成职业判断。" right={<div className="tabs">{(['calendar','timeline','heatmap'] as const).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v==='calendar'?'Calendar':v==='timeline'?'Timeline':'Year Heatmap'}</button>)}</div>}/>
  <div className="journal-layout"><section className="panel journal-main">{view==='calendar'&&<><div className="month"><button aria-label="上个月">‹</button><h3>2026 年 9 月</h3><button aria-label="下个月">›</button></div><div className="calendar labels">{['一','二','三','四','五','六','日'].map(x=><span key={x}>周{x}</span>)}</div><div className="calendar">{days.map((d,i)=>d<1?<span key={`empty-${i}`}/>:<button aria-label={`${d} 日${byDay.has(d)?'，有记录':''}`} key={`day-${d}`} className={`${byDay.has(d)?'has-entry':''} ${selected?.date.endsWith(String(d).padStart(2,'0'))?'selected':''}`} onClick={()=>byDay.has(d)&&select(byDay.get(d)!)}><b>{d}</b>{byDay.has(d)&&<><i/><small>{byDay.get(d)?.title}</small></>}</button>)}</div></>}
   {view==='timeline'&&<div className="timeline">{entries.map(e=><button key={`timeline-${e.id}`} onClick={()=>select(e)} className={selected?.id===e.id?'selected':''}><time>{fmt(e.date)}</time><i/><span><b>{e.title}</b><small>{e.summary}</small></span></button>)}</div>}
   {view==='heatmap'&&<Heatmap entries={entries}/>}</section>
   <EntryDetail entry={selected} openSkill={openSkill}/></div>
 </div>
}
function Heatmap({entries}:{entries:Entry[]}){const hot=new Set(entries.map(e=>e.date)); const cells=Array.from({length:196},(_,i)=>{const d=new Date(2026,2,1+i);const key=d.toISOString().slice(0,10);return {key,level:hot.has(key)?3:(i%29===0?1:0)}});return <div><div className="heatmap-head"><h3>2026 · 记录密度</h3><select><option>Entries</option><option>Evidence</option><option>Important Events</option></select></div><div className="heatmap">{cells.map(c=><i key={c.key} className={`l${c.level}`} title={c.key}/>)}</div><div className="legend"><span>少</span><i/><i className="l1"/><i className="l2"/><i className="l3"/><span>多</span></div></div>}
function EntryDetail({entry,openSkill}:{entry?:Entry;openSkill:(s:SkillKey)=>void}){if(!entry)return <aside className="panel detail empty">选择一条记录查看详情</aside>;const ev=evidence.filter(v=>entry.evidenceIds.includes(v.id));return <aside className="panel detail"><p className="date">{fmt(entry.date)} · {entry.type}</p><h2>{entry.title}</h2><p>{entry.reflection}</p><h3>Career Signal</h3><div className="signal">{entry.signal}</div><h3>Evidence Generated</h3>{ev.length?ev.map(v=><div className="evidence-line" key={v.id}><span>{v.description}</span><b>+{v.strength}</b></div>):<p className="muted">这条随记尚未生成结构化证据。</p>}<h3>Affected Skills</h3><div className="chips">{entry.skills.map(s=><button key={s} onClick={()=>openSkill(s)}>{skills.find(x=>x.id===s)?.name} <ChevronRight/></button>)}</div></aside>}

function SkillMap({role,setRole,selected,select,openEntry}:{role:RoleName;setRole:(r:RoleName)=>void;selected:SkillKey;select:(s:SkillKey)=>void;openEntry:(e:Entry)=>void}){const data=skills.map(s=>({subject:s.name,current:s.current,target:targetFor(s,role)}));const item=skills.find(s=>s.id===selected)!;const ev=evidenceForSkill(selected);return <div className="content"><PageHead title="Skill Map" copy="每一个 Level 都应该能回到具体证据。" right={<RoleSelect role={role} setRole={setRole}/>}/><div className="skill-layout"><section className="panel radar"><div className="legend"><span className="current">Current Me</span><span className="target">{role} Target</span></div><ResponsiveContainer width="100%" height={390}><RadarChart data={data} outerRadius="70%"><PolarGrid stroke="#dfe3eb"/><PolarAngleAxis dataKey="subject" tick={{fontSize:12,fill:'#596173'}}/><Tooltip/><Radar name="Target" dataKey="target" stroke="#929bad" fill="#929bad" fillOpacity={0.08} strokeDasharray="4 4"/><Radar name="Current" dataKey="current" stroke="#1555d6" fill="#1555d6" fillOpacity={0.18} strokeWidth={2}/></RadarChart></ResponsiveContainer><div className="skill-list">{skills.map(s=><button key={s.id} className={selected===s.id?'active':''} onClick={()=>select(s.id)}><span>{s.name}</span><b>L{s.current}</b></button>)}</div></section><section className="panel skill-detail"><p className="eyeline">Gap Detail</p><h2>{item.name}</h2><div className="levels"><div><span>Current</span><b>L{item.current}</b></div><div><span>{role} Target</span><b>L{targetFor(item,role)}</b></div><div className="gap"><span>Gap</span><b>{targetFor(item,role)-item.current}</b></div></div><h3>已有证据</h3>{ev.length?ev.map(v=><button className="supporting" key={v.id} onClick={()=>v.entry&&openEntry(v.entry)}><span><b>{v.description}</b><small>{v.entry?.title} · {fmt(v.date)}</small></span><ChevronRight/></button>):<p className="muted">还没有支持证据。</p>}<h3>缺失证据</h3><ul>{item.missing.map(x=><li key={x}>{x}</li>)}</ul><div className="recommend"><Sparkles/><div><b>Career Agent 建议</b><p>优先争取一次能够产出“{item.missing[0]}”证据的真实任务，并在结束后记录你的判断和结果。</p></div></div></section></div></div>}

function Memory({openEntry,openSkill}:{openEntry:(e:Entry)=>void;openSkill:(s:SkillKey)=>void}){const [filter,setFilter]=useState<'all'|'strong'>('all');const list=filter==='strong'?evidence.filter(e=>e.strength>=3):evidence;return <div className="content"><PageHead title="Career Memory" copy="不是资料仓库，而是能够回溯的职业证据系统。" right={<div className="tabs"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>全部证据</button><button className={filter==='strong'?'active':''} onClick={()=>setFilter('strong')}>强证据</button></div>}/><div className="memory-summary"><div><b>{seedEntries.length}</b><span>Experiences</span></div><div><b>{evidence.length}</b><span>Evidence</span></div><div><b>{skills.length}</b><span>Skills</span></div><div><b>2</b><span>Achievements</span></div></div><section className="panel memory-table"><div className="table-head"><span>职业证据</span><span>关联能力</span><span>强度</span><span>来源</span></div>{list.map(v=>{const e=seedEntries.find(x=>x.id===v.entryId)!;const s=skills.find(x=>x.id===v.skill)!;return <div className="table-row" key={v.id}><button onClick={()=>openEntry(e)}><b>{v.description}</b><small>{fmt(v.date)}</small></button><button className="skill-link" onClick={()=>openSkill(v.skill)}>{s.name}</button><span className="strength">{'●'.repeat(v.strength)}{'○'.repeat(3-v.strength)}</span><button className="source" onClick={()=>openEntry(e)}>{e.title}<ChevronRight/></button></div>})}</section></div>}

function Jobs(){const key='career-agent.jobs.v1';const [rows,setRows]=useState(jobs);const [adding,setAdding]=useState(false);const [ready,setReady]=useState(false);useEffect(()=>{try{const saved=localStorage.getItem(key);if(saved)setRows(JSON.parse(saved))}catch{}finally{setReady(true)}},[]);useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify(rows))},[rows,ready]);return <div className="content"><PageHead title="Job Tracker" copy="独立管理求职流程，把面试反馈转成新的能力缺口。" right={<button className="primary" onClick={()=>setAdding(!adding)}><Plus/>添加机会</button>}/>{adding&&<form className="add-job panel" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);setRows([{company:String(form.get('company')||'New Company'),role:String(form.get('role')||'New Opportunity'),stage:'已投递',date:'09/04',result:'等待',gap:'待识别'},...rows]);setAdding(false)}}><input name="company" aria-label="公司" placeholder="公司" required/><input name="role" aria-label="岗位" placeholder="岗位" required/><button className="primary">保存</button></form>}<section className="panel jobs"><div className="table-head"><span>公司 / 岗位</span><span>申请时间</span><span>阶段</span><span>面试识别的 Gap</span><span>状态</span></div>{rows.map((j,i)=><div className="job-row" key={j.company+j.role+i}><span><b>{j.company}</b><small>{j.role}</small></span><time>{j.date}</time><select value={j.stage} onChange={e=>setRows(rows.map((row,index)=>index===i?{...row,stage:e.target.value}:row))}><option>已投递</option><option>简历筛选</option><option>一面</option><option>二面</option><option>Offer</option></select><span className="gap-tag">{j.gap}</span><span>{j.result}</span></div>)}</section></div>}
